env:
  browser: true
  es2021: true
  node: true

extends: airbnb-base

overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  linebreak-style: 0
  no-console: 0
  no-param-reassign: 0
  eol-last: 0
  no-multiple-empty-lines: ['error', { 'max': 1, 'maxEOF': 0 }]
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  object-curly-spacing: ['error', 'always']
  quotes: ['error']